services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: bot-db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - bot-db:/var/lib/postgresql/data
    networks:
      - bot-network
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgAdmin:/var/lib/pgadmin
    networks:
      - bot-network

networks:
  bot-network:
    name: bot-network
    driver: bridge

volumes:
  bot-db:
    name: bot-db
  pgAdmin:
    name: pgAdmin
